### PR TITLE
Fix profile creation bug

### LINKED ISSUE #34: Error "undefined is not an object"
- It does successfully create and delete products & proposals - just gets an error on trying to show the next screen.

- It does not create a profile, BUT it creates an auth profile. 'humphrey@gmail.com gets created in the firebase 'authentication' db but in our 'profiles' db. This used to work, haven't changed anything since the expo tokens so my guess is that since the creation of profiles relates to those the issue lies in the signup function under store/auth. Expected behaviour is that on signup we should 1. create authentication profile and 2. trigger the creation of our separate profile object with more details than just auth. Check the console on creating a profile, the error is: ...profile created: Object {
  "error": "Could not parse auth token.",
}

### PR DESCRIPTION
**Pull request by SpaghettiC0des**
Closes #34

### CODE REVIEW

File: store/actions/profiles.js [hunk 1]
```diff
@@ -58,13 +60,18 @@ export function createProfile(
   image
 ) {
   return async (dispatch, getState) => {
-    const token = getState().auth.token;
-    const userId = getState().auth.userId;
-
+    // const token = getState().auth.token;
```
Comment (osaisacson) [inline store/actions/profiles.js:63]: We don't need auth tokens anymore?

File: store/actions/profiles.js [hunk 2]
```diff
@@ -58,13 +60,18 @@ export function createProfile(
...
+    // const userId = getState().auth.userId;
```
Comment (osaisacson) [inline store/actions/profiles.js:64]: Please remove, don't just comment out unless there is a reason why we might put it back :)

File: screens/details/ProductDetailScreen.js [hunk 3]
```diff
@@ -31,6 +31,10 @@ const ProductDetailScreen = (props) => {
     state.products.availableProducts.find((prod) => prod.id === productId)
   );
 
+  if (!selectedProduct) {
+    return null;
+  }
+
```
[the remark this answers is not in the document]
Comment (SpaghettiC0des) [reply screens/details/ProductDetailScreen.js:37]: It is just a guard when deleting a product, because delete is happening before the navigation, so the screen rerenders with empty id.

File: store/actions/profiles.js (hunk 1 above)
Comment (SpaghettiC0des) [reply store/actions/profiles.js:63]: It's automatically handled by the SDK, that's why I've also refactored sign-in/sign-out.

File: screens/details/ProductDetailScreen.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (osaisacson) [reply screens/details/ProductDetailScreen.js:37]: Cool, thanks! Then this is likely needed in the proposalDetail screen as well, to fix the proposal delete issue. I can add that though.
