### PR TITLE
Fix blank screen navigation

### LINKED ISSUE #39: Navigating to blank screen
After creating a project, we should navigate to the detail of that project. Currently, we go to a blank screen. Same thing when we delete a project - blank screen.

### PR DESCRIPTION
**Pull request by SpaghettiC0des**
Closes #39

### CODE REVIEW

File: components/UI/ContactDetails.js [hunk 1]
```diff
@@ -13,22 +13,23 @@ const ContactDetails = (props) => {
...
-    objectForDetails && objectForDetails.email ? objectForDetails.email : 'Ingen email';
+  const contactEmail = profile && profile.email ? profile.email : 'Ingen email';
 
   //If we are looking at the details for a product, proposal or project, instead show the specific details for this
   if (props.productId) {
-    const productArray = useSelector((state) => state.products.availableProducts).filter(
-      (prod) => prod.id === props.productId
+    const productArray = useSelector((state) =>
+      state.products.availableProducts.filter((prod) => prod.id === props.productId)
     );
```
Comment (osaisacson) [inline components/UI/ContactDetails.js:31]: Why do we use filter() here and find() above? Just curious :)

Comment (SpaghettiC0des) [reply components/UI/ContactDetails.js:31]: I just moved the`.filter` inside the products array selector, this is the same behavior as the older commit. I'll refactor it on the next issue, to use `find` method. :)
